include theos/makefiles/common.mk

TOOL_NAME = unicorn_pon
unicorn_pon_FILES = main.mm
unicorn_pon_INSTALL_PATH = /Library/PreferenceBundles/AcutusPrefs.bundle
unicorn_pon_LIBRARIES = MobileGestalt

include $(THEOS_MAKE_PATH)/tool.mk
