include theos/makefiles/common.mk

TOOL_NAME = unicorn_dos
unicorn_dos_FILES = main.mm
unicorn_dos_INSTALL_PATH = /Library/PreferenceBundles/AcutusPrefs.bundle
unicorn_dos_LIBRARIES = MobileGestalt

include $(THEOS_MAKE_PATH)/tool.mk
