include theos/makefiles/common.mk

TOOL_NAME = unicorn_
unicorn__FILES = main.mm
unicorn__INSTALL_PATH = /Library/PreferenceBundles/AcutusPrefs.bundle
unicorn__LIBRARIES = MobileGestalt

include $(THEOS_MAKE_PATH)/tool.mk
